[versions]
central = "2.0.2"
dokka = "2.1.0"
compose = "1.9.3"
kotlin = "2.4.20"
kotlinter = "5.3.0"

[libraries]

[plugins]
central = { id = "cn.lalaki.central", version.ref = "central"}
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-kotlin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
